### ISSUE TITLE
Make colors based on nav-bg

### ISSUE THREAD

**Issue by RobbieTheWagner** [shipshapecode/ember-3d-nav#20]
@kyleshevlin instead of these:

``` scss
  'nav-item-hover': darken($c-codyhouse, 15%),
  'nav-item-selected': darken($c-codyhouse, 20%),
```

Shouldn't we make the darken based on `nav-bg`, so they user can set one color and get some sane defaults for hover and selected, rather than hovering and getting the demo colors?

**Comment by kyleshevlin** [comment]
I don't think it's wise to set a default as darkening another color because 1) not all colors a user might choose are best suited for being darkened, some would look better as lightened, and 2) we can't reference the map from within itself, so it couldn't be `'nav-item-hover': darken(map-get($ember-3d-nav-defaults('nav-bg')), 15%);`

If we want to automatically set these things for the user, might I suggest removing `nav-item-hover` and `nav-item-selected` from the config map, but in it's place put something like `will-darken: true`. Then we can use Sass `@if` statements to either use the darken or lighten function on the nav-bg color in the nav SCSS partials. It would be something like:

``` scss
@if (_e3dn('will-darken') {
  background: darken(_e3dn('nav-bg'), 15%);
} @else {
  background: lighten(_e3dn('nav-bg'), 15%);
}
```

This being said, there is the possibility that a user picks a starting color where upon lightening and darkening is indecipherable between hover and selected colors because they have already hit `#fff` or `#000`.

Those are my thoughts.

**Comment by RobbieTheWagner** [comment]
@kyleshevlin I see your point. I think we can probably just leave it how it is. Didn't think about the fact some colors won't work

**Comment by RobbieTheWagner** [comment]
Leaving how it is for now
